### ISSUE TITLE
False order in DS

### ISSUE THREAD

**Issue by animaux** [symphonists/order_entries#69] opened 2015-08-03 14:11 UTC
Using the most recent `order_entries` version on `Symphony 2.6.2` gives me a wrong order when sorting by this field in the DS. E. g. a set of entries with order numbers 

    3, 4, 5

becomes

    3, 5, 4

in the DS-output.

**Comment by animaux** [comment] 2015-08-03 14:12
No change whether I use `asc` or `desc` order. Always `3, 5, 4`.

**Comment by animaux** [comment] 2015-08-03 14:16
Using `<xsl:sort/>` as a workaround meanwhile …

**Comment by nitriques** [comment] 2015-08-07 15:00
> Using the most recent order_entries version 

Do you mean the integration branch ? If not, could you try the integration branch ?

**Comment by nitriques** [comment] 2015-08-10 19:47
ping!

**Comment by animaux** [comment] 2015-08-10 19:47
Sorry! Will check tomorrow :)

**Comment by nitriques** [comment] 2015-08-10 20:05
Ok thanks!

**Comment by animaux** [comment] 2015-08-11 06:22
Sorry, apparently no change in `2.3.0 integration`. Output is still `3, 5, 4`.

**Comment by animaux** [comment] 2015-08-11 06:25
If I try to deactivate ordered filtering I get an SQL-Error: 

    An error occurred while attempting to execute the following query
    ALTER TABLE `sym_entries_data_15` ADD UNIQUE `unique`(`entry_id` ,`field_` );

### Backtrace

    [/…/symphony/lib/toolkit/class.mysql.php:556]
        MySQL->__error();
    [/…/extensions/order_entries/fields/field.order_entries.php:237]
        MySQL->query();
    [/…/extensions/order_entries/fields/field.order_entries.php:269]
        fieldOrder_Entries->updateFilterTable();
    [/…/symphony/content/content.blueprintssections.php:787]
        fieldOrder_Entries->commit();
    [/…/symphony/content/content.blueprintssections.php:883]
        contentBlueprintsSections->__actionNew();
    [/…/symphony/lib/toolkit/class.administrationpage.php:705]
        contentBlueprintsSections->__actionEdit();
    [/…/symphony/lib/toolkit/class.administrationpage.php:668]
        AdministrationPage->__switchboard();
    [/…/symphony/lib/toolkit/class.administrationpage.php:450]
        AdministrationPage->action();
    [/…/symphony/content/content.blueprintssections.php:26]
        AdministrationPage->build();
    [/…/symphony/lib/core/class.administration.php:212]
        contentBlueprintsSections->build();
    [/…/symphony/lib/core/class.administration.php:490]
        Administration->__buildPage();
    [/…/symphony/lib/boot/func.utilities.php:232]
        Administration->display();
    [/…/symphony/lib/boot/func.utilities.php:212]
        symphony_launcher();
    [/…/index.php:17]
        symphony();
    
### Database Query Log

    [0.0010] SET character_set_connection = 'utf8', character_set_database = 'utf8', character_set_server = 'utf8';
    [0.0003] SET CHARACTER SET 'utf8';
    [0.0006] SET time_zone = '+02:00';
    [0.0014] SELECT SQL_CACHE t1.name, t2.page, t2.delegate, t2.callback FROM `sym_extensions` as t1 INNER JOIN `sym_extensions_delegates` as t2 ON t1.id = t2.extension_id WHERE t1.status = 'enabled' ORDER BY t2.delegate, t1.name;
    [0.0003] SELECT SQL_CACHE `name` FROM `sym_extensions` WHERE `status` = 'enabled';
    [0.0003] SELECT SQL_CACHE `session_data` FROM `sym_sessions` WHERE `session` = '9oi3k9bl8e94h68fovcj13j335' LIMIT 1;
    [0.0003] SELECT SQL_CACHE a.* FROM `sym_authors` AS `a` WHERE `username` = 'goldwiege' ORDER BY a.id ASC LIMIT 1;
    [0.0003] UPDATE sym_authors SET `last_seen` = '2015-08-11 08:23:03' WHERE `id` = 1;
    [0.0004] SELECT SQL_CACHE * FROM `sym_extensions`;
    [0.0007] SELECT SQL_CACHE * FROM `sym_sections_association` AS `sa`, `sym_sections` AS `s` WHERE `sa`.`child_section_id` = 2 AND `s`.`id` = `sa`.`parent_section_id` ORDER BY `s`.`sortorder` ASC;
    [0.0008] SELECT SQL_CACHE * FROM `sym_sections_association` AS `sa`, `sym_sections` AS `s` WHERE `sa`.`parent_section_id` = 2 AND `s`.`id` = `sa`.`child_section_id` ORDER BY `s`.`sortorder` ASC;
    [0.0007] SELECT SQL_CACHE `s`.* FROM `sym_sections` AS `s` ORDER BY `s`.`sortorder` asc;
    [0.0019] SELECT SQL_CACHE d.pages, d.id FROM `sym_documentation` AS d ORDER BY d.pages ASC;
    [0.0017] SELECT SQL_CACHE `id` FROM `sym_sections` WHERE `handle` = 'artikel' LIMIT 1;
    [0.0007] UPDATE sym_sections SET `name` = 'Artikel', `handle` = 'artikel', `navigation_group` = 'Inhalt', `hidden` = 'no', `filter` = 'no', `max_entries` = '0' WHERE `id` = 2;
    [0.0005] SELECT SQL_CACHE `id` FROM `sym_fields` WHERE `parent_section` = '2' AND `id` NOT IN ('4', '5', '6', '7', '12', '35', '14', '15');
    [0.0004] UPDATE sym_fields SET `label` = 'Titel', `element_name` = 'titel', `parent_section` = '2', `location` = 'main', `required` = 'yes', `type` = 'input', `show_column` = 'yes', `sortorder` = '0' WHERE `id` = 4;
    [0.0006] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 4 LIMIT 1;
    [0.0005] DELETE FROM `sym_fields_input` WHERE `field_id` = 4 LIMIT 1;
    [0.0004] INSERT INTO `sym_fields_input` (`validator`, `field_id`) VALUES (null, '4');
    [0.0006] UPDATE sym_fields SET `label` = 'Veröffentlicht', `element_name` = 'veroeffentlicht', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'checkbox', `show_column` = 'yes', `sortorder` = '1' WHERE `id` = 5;
    [0.0004] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 5 LIMIT 1;
    [0.0003] DELETE FROM `sym_fields_checkbox` WHERE `field_id` = 5 LIMIT 1;
    [0.0002] INSERT INTO `sym_fields_checkbox` (`default_state`, `field_id`) VALUES ('on', '5');
    [0.0003] UPDATE sym_fields SET `label` = 'Navigationspunkt', `element_name` = 'navigationspunkt', `parent_section` = '2', `location` = 'sidebar', `required` = 'yes', `type` = 'association', `show_column` = 'yes', `sortorder` = '2' WHERE `id` = 6;
    [0.0002] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 6 LIMIT 1;
    [0.0003] DELETE FROM `sym_fields_association` WHERE `field_id` = 6 LIMIT 1;
    [0.0003] INSERT INTO `sym_fields_association` (`field_id`, `related_field_id`, `allow_multiple_selection`, `hide_when_prepopulated`, `limit`) VALUES ('6', '1', 'no', 'no', '20');
    [0.0003] DELETE FROM sym_sections_association WHERE `child_section_field_id` = 6 OR `parent_section_field_id` = 6;
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(1);
    [0.0002] SELECT SQL_CACHE * FROM `sym_fields_input` WHERE `field_id` IN (1);
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(6);
    [0.0003] SELECT SQL_CACHE * FROM `sym_fields_association` WHERE `field_id` IN (6);
    [0.0006] SELECT SQL_CACHE CASE hide_association WHEN "no" THEN "yes" ELSE "no" END as show_association FROM `sym_sections_association` WHERE `child_section_field_id` = 6;
    [0.0003] INSERT INTO `sym_sections_association` (`parent_section_id`, `parent_section_field_id`, `child_section_id`, `child_section_field_id`, `hide_association`, `interface`, `editor`) VALUES ('1', '1', '2', '6', 'no', 'aui-selector-sortable', null);
    [0.0003] UPDATE sym_fields SET `label` = 'Text', `element_name` = 'text', `parent_section` = '2', `location` = 'main', `required` = 'no', `type` = 'textarea', `show_column` = 'no', `sortorder` = '3' WHERE `id` = 7;
    [0.0003] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 7 LIMIT 1;
    [0.0003] DELETE FROM `sym_fields_textarea` WHERE `field_id` = 7 LIMIT 1;
    [0.0003] INSERT INTO `sym_fields_textarea` (`formatter`, `size`, `field_id`) VALUES ('markdown_extra_with_smartypants', '15', '7');
    [0.0005] UPDATE sym_fields SET `label` = 'Titelbild', `element_name` = 'titelbild', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'association', `show_column` = 'no', `sortorder` = '4' WHERE `id` = 12;
    [0.0003] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 12 LIMIT 1;
    [0.0002] DELETE FROM `sym_fields_association` WHERE `field_id` = 12 LIMIT 1;
    [0.0004] INSERT INTO `sym_fields_association` (`field_id`, `related_field_id`, `allow_multiple_selection`, `hide_when_prepopulated`, `limit`) VALUES ('12', '13', 'no', 'no', '20');
    [0.0003] DELETE FROM sym_sections_association WHERE `child_section_field_id` = 12 OR `parent_section_field_id` = 12;
    [0.0004] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(13);
    [0.0003] SELECT SQL_CACHE * FROM `sym_fields_reflection` WHERE `field_id` IN (13);
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(12);
    [0.0004] SELECT SQL_CACHE * FROM `sym_fields_association` WHERE `field_id` IN (12);
    [0.0004] SELECT SQL_CACHE CASE hide_association WHEN "no" THEN "yes" ELSE "no" END as show_association FROM `sym_sections_association` WHERE `child_section_field_id` = 12;
    [0.0002] INSERT INTO `sym_sections_association` (`parent_section_id`, `parent_section_field_id`, `child_section_id`, `child_section_field_id`, `hide_association`, `interface`, `editor`) VALUES ('3', '13', '2', '12', 'no', 'aui-selector-sortable', 'aui-editor-new');
    [0.0004] UPDATE sym_fields SET `label` = 'Bildergalerie', `element_name` = 'bilder', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'association', `show_column` = 'no', `sortorder` = '5' WHERE `id` = 35;
    [0.0003] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 35 LIMIT 1;
    [0.0007] DELETE FROM `sym_fields_association` WHERE `field_id` = 35 LIMIT 1;
    [0.0017] INSERT INTO `sym_fields_association` (`field_id`, `related_field_id`, `allow_multiple_selection`, `hide_when_prepopulated`, `limit`) VALUES ('35', '13', 'yes', 'no', '20');
    [0.0017] DELETE FROM sym_sections_association WHERE `child_section_field_id` = 35 OR `parent_section_field_id` = 35;
    [0.0017] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(35);
    [0.0016] SELECT SQL_CACHE * FROM `sym_fields_association` WHERE `field_id` IN (35);
    [0.0003] SELECT SQL_CACHE CASE hide_association WHEN "no" THEN "yes" ELSE "no" END as show_association FROM `sym_sections_association` WHERE `child_section_field_id` = 35;
    [0.0003] INSERT INTO `sym_sections_association` (`parent_section_id`, `parent_section_field_id`, `child_section_id`, `child_section_field_id`, `hide_association`, `interface`, `editor`) VALUES ('3', '13', '2', '35', 'no', 'aui-selector-sortable', 'aui-editor-new');
    [0.0005] UPDATE sym_fields SET `label` = 'Downloads', `element_name` = 'downloads', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'association', `show_column` = 'no', `sortorder` = '6' WHERE `id` = 14;
    [0.0003] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 14 LIMIT 1;
    [0.0007] DELETE FROM `sym_fields_association` WHERE `field_id` = 14 LIMIT 1;
    [0.0006] INSERT INTO `sym_fields_association` (`field_id`, `related_field_id`, `allow_multiple_selection`, `hide_when_prepopulated`, `limit`) VALUES ('14', '10', 'yes', 'no', '20');
    [0.0005] DELETE FROM sym_sections_association WHERE `child_section_field_id` = 14 OR `parent_section_field_id` = 14;
    [0.0008] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(10);
    [0.0014] SELECT SQL_CACHE * FROM `sym_fields_input` WHERE `field_id` IN (10);
    [0.0005] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(14);
    [0.0005] SELECT SQL_CACHE * FROM `sym_fields_association` WHERE `field_id` IN (14);
    [0.0003] SELECT SQL_CACHE CASE hide_association WHEN "no" THEN "yes" ELSE "no" END as show_association FROM `sym_sections_association` WHERE `child_section_field_id` = 14;
    [0.0003] INSERT INTO `sym_sections_association` (`parent_section_id`, `parent_section_field_id`, `child_section_id`, `child_section_field_id`, `hide_association`, `interface`, `editor`) VALUES ('4', '10', '2', '14', 'no', 'aui-selector-sortable', 'aui-editor-new');
    [0.0003] UPDATE sym_fields SET `label` = 'Reihenfolge', `element_name` = 'reihenfolge', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'order_entries', `show_column` = 'yes', `sortorder` = '7' WHERE `id` = 15;
    [0.0015] SHOW COLUMNS FROM sym_entries_data_15 WHERE Field like 'field_%';;
    [0.0021] ALTER TABLE `sym_entries_data_15` DROP COLUMN `field_6`;
    [0.0017] ALTER TABLE `sym_entries_data_15` DROP INDEX `unique`;;

**Comment by animaux** [comment] 2015-08-11 06:27
If I try to disable pagination I get:

    Symphony Fatal Database Error: Can't DROP 'unique'; check that column/key exists
    An error occurred while attempting to execute the following query
    ALTER TABLE `sym_entries_data_15` DROP INDEX `unique`;

### Backtrace

    [/…/symphony/lib/toolkit/class.mysql.php:556]
        MySQL->__error();
    [/…/extensions/order_entries/fields/field.order_entries.php:236]
        MySQL->query();
    [/…/extensions/order_entries/fields/field.order_entries.php:269]
        fieldOrder_Entries->updateFilterTable();
    [/…/symphony/content/content.blueprintssections.php:787]
        fieldOrder_Entries->commit();
    [/…/symphony/content/content.blueprintssections.php:883]
        contentBlueprintsSections->__actionNew();
    [/…/symphony/lib/toolkit/class.administrationpage.php:705]
        contentBlueprintsSections->__actionEdit();
    [/…/symphony/lib/toolkit/class.administrationpage.php:668]
        AdministrationPage->__switchboard();
    [/…/symphony/lib/toolkit/class.administrationpage.php:450]
        AdministrationPage->action();
    [/…/symphony/content/content.blueprintssections.php:26]
        AdministrationPage->build();
    [/…/symphony/lib/core/class.administration.php:212]
        contentBlueprintsSections->build();
    [/…/symphony/lib/core/class.administration.php:490]
        Administration->__buildPage();
    [/…/symphony/lib/boot/func.utilities.php:232]
        Administration->display();
    [/…/symphony/lib/boot/func.utilities.php:212]
        symphony_launcher();
    [/…/index.php:17]
        symphony();

### Database Query Log

    [0.0009] SET character_set_connection = 'utf8', character_set_database = 'utf8', character_set_server = 'utf8';
    [0.0002] SET CHARACTER SET 'utf8';
    [0.0002] SET time_zone = '+02:00';
    [0.0010] SELECT SQL_CACHE t1.name, t2.page, t2.delegate, t2.callback FROM `sym_extensions` as t1 INNER JOIN `sym_extensions_delegates` as t2 ON t1.id = t2.extension_id WHERE t1.status = 'enabled' ORDER BY t2.delegate, t1.name;
    [0.0005] SELECT SQL_CACHE `name` FROM `sym_extensions` WHERE `status` = 'enabled';
    [0.0004] SELECT SQL_CACHE `session_data` FROM `sym_sessions` WHERE `session` = '9oi3k9bl8e94h68fovcj13j335' LIMIT 1;
    [0.0005] DELETE FROM `sym_sessions` WHERE `session_expires` <= 1438064748;
    [0.0005] SELECT SQL_CACHE a.* FROM `sym_authors` AS `a` WHERE `username` = 'goldwiege' ORDER BY a.id ASC LIMIT 1;
    [0.0003] UPDATE sym_authors SET `last_seen` = '2015-08-11 08:25:48' WHERE `id` = 1;
    [0.0003] SELECT SQL_CACHE * FROM `sym_extensions`;
    [0.0005] SELECT SQL_CACHE * FROM `sym_sections_association` AS `sa`, `sym_sections` AS `s` WHERE `sa`.`child_section_id` = 2 AND `s`.`id` = `sa`.`parent_section_id` ORDER BY `s`.`sortorder` ASC;
    [0.0003] SELECT SQL_CACHE * FROM `sym_sections_association` AS `sa`, `sym_sections` AS `s` WHERE `sa`.`parent_section_id` = 2 AND `s`.`id` = `sa`.`child_section_id` ORDER BY `s`.`sortorder` ASC;
    [0.0003] SELECT SQL_CACHE `s`.* FROM `sym_sections` AS `s` ORDER BY `s`.`sortorder` asc;
    [0.0004] SELECT SQL_CACHE d.pages, d.id FROM `sym_documentation` AS d ORDER BY d.pages ASC;
    [0.0003] SELECT SQL_CACHE `id` FROM `sym_sections` WHERE `handle` = 'artikel' LIMIT 1;
    [0.0002] UPDATE sym_sections SET `name` = 'Artikel', `handle` = 'artikel', `navigation_group` = 'Inhalt', `hidden` = 'no', `filter` = 'no', `max_entries` = '0' WHERE `id` = 2;
    [0.0003] SELECT SQL_CACHE `id` FROM `sym_fields` WHERE `parent_section` = '2' AND `id` NOT IN ('4', '5', '6', '7', '12', '35', '14', '15');
    [0.0003] UPDATE sym_fields SET `label` = 'Titel', `element_name` = 'titel', `parent_section` = '2', `location` = 'main', `required` = 'yes', `type` = 'input', `show_column` = 'yes', `sortorder` = '0' WHERE `id` = 4;
    [0.0003] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 4 LIMIT 1;
    [0.0003] DELETE FROM `sym_fields_input` WHERE `field_id` = 4 LIMIT 1;
    [0.0002] INSERT INTO `sym_fields_input` (`validator`, `field_id`) VALUES (null, '4');
    [0.0004] UPDATE sym_fields SET `label` = 'Veröffentlicht', `element_name` = 'veroeffentlicht', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'checkbox', `show_column` = 'yes', `sortorder` = '1' WHERE `id` = 5;
    [0.0008] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 5 LIMIT 1;
    [0.0003] DELETE FROM `sym_fields_checkbox` WHERE `field_id` = 5 LIMIT 1;
    [0.0003] INSERT INTO `sym_fields_checkbox` (`default_state`, `field_id`) VALUES ('on', '5');
    [0.0003] UPDATE sym_fields SET `label` = 'Navigationspunkt', `element_name` = 'navigationspunkt', `parent_section` = '2', `location` = 'sidebar', `required` = 'yes', `type` = 'association', `show_column` = 'yes', `sortorder` = '2' WHERE `id` = 6;
    [0.0003] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 6 LIMIT 1;
    [0.0003] DELETE FROM `sym_fields_association` WHERE `field_id` = 6 LIMIT 1;
    [0.0002] INSERT INTO `sym_fields_association` (`field_id`, `related_field_id`, `allow_multiple_selection`, `hide_when_prepopulated`, `limit`) VALUES ('6', '1', 'no', 'no', '20');
    [0.0003] DELETE FROM sym_sections_association WHERE `child_section_field_id` = 6 OR `parent_section_field_id` = 6;
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(1);
    [0.0003] SELECT SQL_CACHE * FROM `sym_fields_input` WHERE `field_id` IN (1);
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(6);
    [0.0004] SELECT SQL_CACHE * FROM `sym_fields_association` WHERE `field_id` IN (6);
    [0.0003] SELECT SQL_CACHE CASE hide_association WHEN "no" THEN "yes" ELSE "no" END as show_association FROM `sym_sections_association` WHERE `child_section_field_id` = 6;
    [0.0003] INSERT INTO `sym_sections_association` (`parent_section_id`, `parent_section_field_id`, `child_section_id`, `child_section_field_id`, `hide_association`, `interface`, `editor`) VALUES ('1', '1', '2', '6', 'no', 'aui-selector-sortable', null);
    [0.0004] UPDATE sym_fields SET `label` = 'Text', `element_name` = 'text', `parent_section` = '2', `location` = 'main', `required` = 'no', `type` = 'textarea', `show_column` = 'no', `sortorder` = '3' WHERE `id` = 7;
    [0.0003] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 7 LIMIT 1;
    [0.0003] DELETE FROM `sym_fields_textarea` WHERE `field_id` = 7 LIMIT 1;
    [0.0003] INSERT INTO `sym_fields_textarea` (`formatter`, `size`, `field_id`) VALUES ('markdown_extra_with_smartypants', '15', '7');
    [0.0003] UPDATE sym_fields SET `label` = 'Titelbild', `element_name` = 'titelbild', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'association', `show_column` = 'no', `sortorder` = '4' WHERE `id` = 12;
    [0.0002] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 12 LIMIT 1;
    [0.0002] DELETE FROM `sym_fields_association` WHERE `field_id` = 12 LIMIT 1;
    [0.0002] INSERT INTO `sym_fields_association` (`field_id`, `related_field_id`, `allow_multiple_selection`, `hide_when_prepopulated`, `limit`) VALUES ('12', '13', 'no', 'no', '20');
    [0.0003] DELETE FROM sym_sections_association WHERE `child_section_field_id` = 12 OR `parent_section_field_id` = 12;
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(13);
    [0.0003] SELECT SQL_CACHE * FROM `sym_fields_reflection` WHERE `field_id` IN (13);
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(12);
    [0.0003] SELECT SQL_CACHE * FROM `sym_fields_association` WHERE `field_id` IN (12);
    [0.0003] SELECT SQL_CACHE CASE hide_association WHEN "no" THEN "yes" ELSE "no" END as show_association FROM `sym_sections_association` WHERE `child_section_field_id` = 12;
    [0.0009] INSERT INTO `sym_sections_association` (`parent_section_id`, `parent_section_field_id`, `child_section_id`, `child_section_field_id`, `hide_association`, `interface`, `editor`) VALUES ('3', '13', '2', '12', 'no', 'aui-selector-sortable', 'aui-editor-new');
    [0.0002] UPDATE sym_fields SET `label` = 'Bildergalerie', `element_name` = 'bilder', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'association', `show_column` = 'no', `sortorder` = '5' WHERE `id` = 35;
    [0.0002] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 35 LIMIT 1;
    [0.0002] DELETE FROM `sym_fields_association` WHERE `field_id` = 35 LIMIT 1;
    [0.0003] INSERT INTO `sym_fields_association` (`field_id`, `related_field_id`, `allow_multiple_selection`, `hide_when_prepopulated`, `limit`) VALUES ('35', '13', 'yes', 'no', '20');
    [0.0003] DELETE FROM sym_sections_association WHERE `child_section_field_id` = 35 OR `parent_section_field_id` = 35;
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(35);
    [0.0003] SELECT SQL_CACHE * FROM `sym_fields_association` WHERE `field_id` IN (35);
    [0.0003] SELECT SQL_CACHE CASE hide_association WHEN "no" THEN "yes" ELSE "no" END as show_association FROM `sym_sections_association` WHERE `child_section_field_id` = 35;
    [0.0003] INSERT INTO `sym_sections_association` (`parent_section_id`, `parent_section_field_id`, `child_section_id`, `child_section_field_id`, `hide_association`, `interface`, `editor`) VALUES ('3', '13', '2', '35', 'no', 'aui-selector-sortable', 'aui-editor-new');
    [0.0002] UPDATE sym_fields SET `label` = 'Downloads', `element_name` = 'downloads', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'association', `show_column` = 'no', `sortorder` = '6' WHERE `id` = 14;
    [0.0002] SELECT SQL_CACHE `type` FROM `sym_fields` WHERE `id` = 14 LIMIT 1;
    [0.0002] DELETE FROM `sym_fields_association` WHERE `field_id` = 14 LIMIT 1;
    [0.0002] INSERT INTO `sym_fields_association` (`field_id`, `related_field_id`, `allow_multiple_selection`, `hide_when_prepopulated`, `limit`) VALUES ('14', '10', 'yes', 'no', '20');
    [0.0002] DELETE FROM sym_sections_association WHERE `child_section_field_id` = 14 OR `parent_section_field_id` = 14;
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(10);
    [0.0002] SELECT SQL_CACHE * FROM `sym_fields_input` WHERE `field_id` IN (10);
    [0.0003] SELECT SQL_CACHE t1.* FROM sym_fields AS `t1` WHERE 1 AND t1.`id` IN(14);
    [0.0003] SELECT SQL_CACHE * FROM `sym_fields_association` WHERE `field_id` IN (14);
    [0.0002] SELECT SQL_CACHE CASE hide_association WHEN "no" THEN "yes" ELSE "no" END as show_association FROM `sym_sections_association` WHERE `child_section_field_id` = 14;
    [0.0003] INSERT INTO `sym_sections_association` (`parent_section_id`, `parent_section_field_id`, `child_section_id`, `child_section_field_id`, `hide_association`, `interface`, `editor`) VALUES ('4', '10', '2', '14', 'no', 'aui-selector-sortable', 'aui-editor-new');
    [0.0002] UPDATE sym_fields SET `label` = 'Reihenfolge', `element_name` = 'reihenfolge', `parent_section` = '2', `location` = 'sidebar', `required` = 'no', `type` = 'order_entries', `show_column` = 'yes', `sortorder` = '7' WHERE `id` = 15;
    [0.0014] SHOW COLUMNS FROM sym_entries_data_15 WHERE Field like 'field_%';;
    [0.0015] ALTER TABLE `sym_entries_data_15` ADD COLUMN `field_6`varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL;

**Comment by nitriques** [comment] 2015-08-11 13:57
Wow that sucks hard. Thanks, I'll try to fix ASAP.

**Comment by animaux** [comment] 2015-08-11 14:02
No worries, the current workaround runs fine for the moment :)

**Comment by animaux** [comment] 2015-08-13 12:42
As a sidenote: 2.3.0 totally borked another installation of Symphony 2.6.2. Going back to 2.2.x helps, but brings back other know issues …

**Comment by nitriques** [comment] 2015-08-13 15:33
Latest version do not support 2.3.x https://github.com/symphonists/order_entries/blob/master/extension.meta.xml#L21-L27

**Comment by animaux** [comment] 2015-08-17 12:37
N’ah, I meant `order_entries 2.3`.

**Comment by nitriques** [comment] 2015-08-18 15:01
Oh. And which version of Symphony ?

cc @jonmifsud

**Comment by animaux** [comment] 2015-08-18 15:04
`2.6.2`

**Comment by nitriques** [comment] 2015-08-18 15:14
> If I try to deactivate ordered filtering I get an SQL-Error:

How did you try to deactivate it ? Deleting the field ? Or the extension ?

**Comment by jonmifsud** [comment] 2015-08-18 15:55
@animaux is it just the Order in the datasource or you had other issues ? I'll try to get to the bottom of this.

**Comment by animaux** [comment] 2015-08-18 15:55
I meant unchecking »ordering filtering« in the section editor.

**Comment by animaux** [comment] 2015-08-18 15:56
@jonmifsud I had the database errors mentioned above too.

**Comment by nitriques** [comment] 2015-08-18 18:43
> @nitriques I meant unchecking »ordering filtering« in the section editor.

Ok, that, I know why.

**Comment by jonmifsud** [comment] 2015-08-21 13:51
@animaux I'll have a fix today figured out the issue, at least when using filtering not sure if it could have had some side effects on unfiltered results. should be sending a PR shortly will keep you posted.

**Comment by jonmifsud** [comment] 2015-08-26 07:28
@nitriques got a copy of the site from @animaux. The problem is mainly a documentation related one with how to use the added Order Filtering. Maybe you can suggest a way to make it more solid.

The use case, at least for me and how I understand it is this:

Only enable Order Filtering if you want separate order per filter value. Your filters both backend and frontend would have to match for the specified fields for the data to pull up. I think it makes sense to give a few examples maybe with screenshots might not be the easiest of concepts to grasp.

**Comment by nitriques** [comment] 2015-08-26 17:24
@jonmifsud yeah why not!

**Comment by nitriques** [comment] 2015-10-07 21:34
SO is this closed ? I've merged with https://github.com/symphonists/order_entries/compare/integration...jonmifsud:fixorderxml

**Closed** 2015-10-07 21:50 UTC
