### ISSUE TITLE
After deleting one entry all order values turn to 0

### ISSUE THREAD

**Issue by mprofitl** [symphonists/order_entries#86] opened 2017-10-28 09:42 UTC
In a new installation I experience a problem I never had. When deleting an entry (from a filtered view) that has been ordered through an order_entries field, the order number of all entries of that filtered view (and only of it) turn to 0. I did not activate filtered ordering and I forced manual ordering. My version is 2.3.7.

**Comment by mprofitl** [comment] 2017-10-28 10:07
That was hard to find. I suggest to complement the manual with this hint:

When ordering entries with images, order_entries must not be the only other visible field (this might only apply when using the image index preview extension). Another field like a textfield or an association must be visible as well. Otherwise deleting an entry will set all visible order entries to 0.

**Comment by nitriques** [comment] 2017-11-09 01:38
This is PRETTY weird. Did you confirm that it's the extension ?

**Comment by nitriques** [comment] 2017-11-09 01:43
I do not seems to be able to reproduce... Can you link to the extension you are talking about please ?

**Comment by mprofitl** [comment] 2017-11-09 08:55
I will prepare a little test situation and send you a login for it. I will need to let you wait until the weekend however.

**Comment by nitriques** [comment] 2017-11-14 01:11
Great! Thanks @mprofitl

**Comment by mprofitl** [comment] 2019-01-15 20:07
@nitriques Sorry for letting you wait so long. I now set up a test. Looking a the problem again it turned out that not images are the problem nor filtered views: Order entries must not be the first visible field, it must not be in the first column. In case you would like to see the test installation, could you please tell me to which address I may send the login?

**Comment by nitriques** [comment] 2019-01-22 21:35
Ah! Yes! I do not know if we can fix that easily. But I was able to reproduce!

**Comment by nitriques** [comment] 2019-01-22 21:43
Fixed in `2.3.9` !

**Closed** 2019-01-22 21:43 UTC
Labels: Bug, More info needed
